phosphor-state-manager: srcrev bump 0d1c3f1f93..0a675215d6
Patrick Williams (2):
      cleanup sdbus CAMELCASE define
      exception: switch to public sdbus exception

Change-Id: Id83d11975ab09247c61b488f713d4c319bd4cde8
Signed-off-by: Andrew Geissler <openbmcbump-github@yahoo.com>