meta-phosphor: remove installs on templated services and targets
New yocto is getting more stringent on installation of templated service
and targets.

Templated services are installed by bitbake recipes so there's no
need to have the WantedBy/RequiredBy in those services.

Here's a summary of the error we get for packages which have templated
services doing an install:
```
ERROR: obmc-phosphor-image-1.0-r0 do_rootfs: Postinstall scriptlets of
['<package>' 'inst returned 1, marking as unpacked only, configuration
required on target']
If the intention is to defer them to first boot,
then please place them into pkg_postinst_ontarget:${PN} ().
Deferring to first boot via 'exit 1' is no longer supported.
```

Tested:
- Confirmed image builds with new yocto and services are still installed
  as expected

Change-Id: I9dddcc0d51d305c73512d148561fbff27d1a8ff8
Signed-off-by: Andrew Geissler <geissonator@yahoo.com>