meta-ampere: fix postinstall scriptlets error
Fix compilation error after subtree update:
   ERROR: obmc-phosphor-image-1.0-r0 do_rootfs: Postinstall scriptlets of
      ['ampere-sysfw-hang-handler'] have failed. If the intention is to
      defer them to first boot, then please place them into
      pkg_postinst_ontarget:${PN} ().
   Deferring to first boot via 'exit 1' is no longer supported.

Tested:
1. Compile Mt.Jade and Mt.Mitchell without error
2. Check ampere-boot-progress and ampere-sysfw-hang-handler work.

Signed-off-by: Thang Q. Nguyen <thang@os.amperecomputing.com>
Change-Id: I5d692cb4078df05ac20ace34429463ea4e9c18ca