phosphor-virtual-sensor: srcrev bump fbd7145e2d..74c1e7d8c5
Patrick Williams (1):
      exception: switch to public sdbus exception

Change-Id: I9a295ce898deeb448c70c23ad58ca744aa68c194
Signed-off-by: Andrew Geissler <openbmcbump-github@yahoo.com>