openpower-proc-control: srcrev bump 07e9a6a1cc..2246cca047
Patrick Williams (2):
      cleanup sdbus CAMELCASE define
      exception: switch to public sdbus exception

Change-Id: I779bebeeacc5e68178bf64a1aedd2f2d4fe2c715
Signed-off-by: Andrew Geissler <openbmcbump-github@yahoo.com>