openpower-vpd-parser: srcrev bump ed609affb6..8be4334fd9
Patrick Williams (1):
      exception: switch to public sdbus exception

Change-Id: Ib9e4097e719fd340c8c2f653104a82af11f89b60
Signed-off-by: Andrew Geissler <openbmcbump-github@yahoo.com>