phosphor-time-manager: srcrev bump 9c02e7ec0a..295b96b743
Patrick Williams (1):
      exception: switch to public sdbus exception

Change-Id: I6b4adf1b7391bf0fdc95cb89439f350f523344f1
Signed-off-by: Andrew Geissler <openbmcbump-github@yahoo.com>