Specify len() of object by converting to list
Helps resolve the following error in python3:
TypeError: object of type 'filter' has no len()

Change-Id: Id607186baeacc3802f651d5cb72af82d0c10115b
Signed-off-by: Saqib Khan <khansa@us.ibm.com>