dbus-sdr: fix build error when enable sel-logger-clears-sel
Symptom:
When enable -Dsel-logger-clears-sel=enabled,
there is build error in function ipmiStorageClearSEL() as below:

error: 'ctx' was not declared in this scope
|     ctx->bus->yield_method_call<>(ctx->yield, ec, selLoggerServiceName,
error: expected primary-expression before '>' token
|     ctx->bus->yield_method_call<>(ctx->yield, ec, selLoggerServiceName,

Root cause:
There is no define "ctx" in ipmiStorageClearSEL() definition.
ipmi::RspType<uint8_t> ipmiStorageClearSEL(ipmi::Context::ptr,

Solution:
Add define "ctx" for ipmi context pointer.
ipmi::RspType<uint8_t> ipmiStorageClearSEL(ipmi::Context::ptr ctx,

Verified:
bitbake phosphor-ipmi-host and build pass without errors.

Signed-off-by: Tim Lee <timlee660101@gmail.com>