fby35: Disable tpm_tis_i2c
fby35 uses a SPI TPM interface, not the I2C interface, and the I2C module produces compilation
warnings, and build failures with -Werror, so we should disable it
until it's fixed in the kernel.

Building fby35:
```
. setup fby35 build
bitbake obmc-phosphor-image
```

Before:
```
| /home/pdel/lfopenbmc/build/tmp/work-shared/fby35/kernel-source/drivers/char/tpm/tpm_tis_i2c.c: In function 'tpm_tis_i2c_write_bytes':
| /home/pdel/lfopenbmc/build/tmp/work-shared/fby35/kernel-source/drivers/char/tpm/tpm_tis_i2c.c:114:17: error: ISO C90 forbids mixed declarati
ons and code [-Werror=declaration-after-statement]
|   114 |                 struct i2c_msg msgs[] = {
|       |                 ^~~~~~
```

After:
Compiles successfully.

Change-Id: Ib57bcad51837956d8a277d2be1ff7c887ade9606
Signed-off-by: Peter Delevoryas <peter@pjd.dev>