phosphor-user-manager: srcrev bump 607ed50ae1..372c5668c0
Alexander Filippov (1):
      LDAP: start or stop nslcd on service starting

Patrick Williams (2):
      cleanup sdbus CAMELCASE define
      exception: switch to public sdbus exception

Change-Id: Ie6368af14674527496153a31c8c87fdcbf5b0808
Signed-off-by: Andrew Geissler <openbmcbump-github@yahoo.com>