phosphor-ipmi-flash: srcrev bump 4bb6bdf3f6..1c0fe13431
Patrick Williams (1):
      exception: switch to public sdbus exception

Change-Id: I7efc7130b70224369e2ed282059a3cd7a30ac59f
Signed-off-by: Andrew Geissler <openbmcbump-github@yahoo.com>