Revert "meta-nuvoton: npcm8xx-bootloader: update IGPS to 04.03.07"
This reverts commit a84c4de718984e9f19fee786850319c8508ef7db.

The bump to 04.03.05 introduces the following build error:

```
replacing MC_CONFIG value 0x04 to 0x04
Traceback (most recent call last):
  File "tmp/work/evb_npcm845-openbmc-linux/npcm8xx-bootloader/04.03.07/git/py_scripts/ImageGeneration/config_replacer.py", line 318, in <module>
    replace_value_in_py(os.path.join(KEY_SETTINGS_PATH, config),
    ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                        settings[config])
                        ^^^^^^^^^^^^^^^^^
  File "tmp/work/evb_npcm845-openbmc-linux/npcm8xx-bootloader/04.03.07/git/py_scripts/ImageGeneration/config_replacer.py", line 214, in replace_value_in_py
    cp.read(py_file)
    ~~~~~~~^^^^^^^^^
  File "tmp/work/evb_npcm845-openbmc-linux/npcm8xx-bootloader/04.03.07/git/py_scripts/ImageGeneration/config_replacer.py", line 176, in read
    with open(file) as lines:
         ~~~~^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'py_scripts/ImageGeneration/key_setting_edit_me.py'
WARNING: exit code 1 from a shell command.
ERROR: Task (meta-nuvoton/recipes-bsp/images/npcm8xx-bootloader_04.03.07.bb:do_configure) failed with exit code '1'
```

Change-Id: Iff1ee3aa1d2180281bf975f721e68282fc1dc7f4
Signed-off-by: Andrew Jeffery <andrew@codeconstruct.com.au>