Reapply boost library filtering
6be1787fdc13405fa9daa6755c28534bbcaa7458 reverted this change
temporarily to get around a yocto recipe refactor that was preventing us
from upgrading cleanly.  Unfortunately, there's nothing more permanent
than a temporary hack, so this patch never got reapplied.
Recently, we've had issues with Palmetto failing to build boost::regex
with an error:
./boost/regex/v5/mem_block_cache.hpp:91:11: error: 'static_mutex' in
namespace 'boost' does not name a type

Considering OpenBMC doesn't use boost regex (or a bunch of the other
boost libraries) we shouldn't be building them.

For reference, 57acb4680f999e0b2ab96e87fa5313defddeb577 was the original
patch, and contains more details on the advantages of this, but the keys
are we reduce the build times significantly by only building the two
libraries OpenBMC uses, and we avoid bugs like this in boost modules we
don't care about, as we're only building the modules we use.

Signed-off-by: Ed Tanous <edtanous@google.com>
Change-Id: I4006618c6553d72bf7f47baadb0c3e35e141bdc9