meta-evb-fvp-base: move wic files to fix build error
OpenEmbedded-Core (OE-Core) now requires wic files to be placed under
the files/wic path[1].

[1]: https://docs.yoctoproject.org/dev/migration-guides/migration-6.0.html#wic-files-to-be-moved-under-files-wic

Testing:
(Before Fix)
```bash
ERROR: OE-core's config sanity checker detected a potential misconfiguration.
Either fix the cause of this error or at your own risk disable the checker (see sanity.conf).
Following is the list of potential problems / advisories:

wic/wks files at /home/javith/openbmc/meta-evb/meta-evb-arm/meta-evb-fvp-base/wic need to be moved to files/wic within the layer to be found/used
wic/wks files at /home/javith/openbmc/meta-evb/meta-evb-arm/meta-evb-fvp-base/wic need to be moved to files/wic within the layer to be found/used
```

Change-Id: I8978b3c9d25280a224b846da0bc26303fb9b8f57
Signed-off-by: Mohammed Javith Akthar M <mohammedjavitham@ami.com>