meta-nuvoton: evb-npcm845: remove tpm2-tools
The new configuration from tpm2.inc includes tpm2-tools by default.
This causes the image size to exceed the limit, resulting in a build
error. Thus, remove it to reduce the image size on evb-npcm845.

ERROR: obmc-phosphor-image-1.0-r0 do_generate_static:
Image '.../obmc-phosphor-image-evb-npcm845-stage.squashfs-xz'
is 6586368 bytes too large!

Signed-off-by: Tim Lee <timlee660101@gmail.com>
Change-Id: I3616fb7215efb92a8ff3ed999c6853c8ec3d2899