stdplus: srcrev bump eac8771813..500b061737
William A. Kennington III (14):
      variant: Fix missing pragma once
      treewide: Cleanup inline constexpr
      exception: Add error for incomplete operations
      test/fd: Split out some utility functions
      fd/ops: Exact operations to differentiate incomplete and blocking
      fd/ops: Fix aligned ops to return incomplete
      fd/ops: Remove bad accept function
      fd/ops: Fix accept() address return
      fd/impl: Make common check routine
      concepts: Add Enum concept
      flags: Utilize underlying_type for more expressiveness
      flags: Make all operations constexpr compatible
      flags: Allow flag to set conversion
      treewide: Remove use of c++23 in headers

Change-Id: Iaf50864477340e69a4e6fcd69c4257a5208e2c5c
Signed-off-by: Andrew Geissler <openbmcbump-github@yahoo.com>