stdplus: srcrev bump aa4fcfc208..7df61dfc07
William A. Kennington III (9):
      zstring_view: Add class
      zstring_view: Ensure no type coercion
      build: Propagate function2
      exception: Use source_location instead of compiler builtins
      exception: Fix for older clang
      zstring_view: Fix coercion
      zstring: Add class
      zstring: Fix conversion for string references
      exception: Fix noexcept and source location

Change-Id: If756f84a2ebc0c54a3900178cb4441b7ed0439b5
Signed-off-by: Andrew Geissler <openbmcbump-github@yahoo.com>