phosphor-debug-collector: srcrev bump f4694d714f..52ac69c152
Patrick Williams (2):
      cleanup sdbus CAMELCASE define
      exception: switch to public sdbus exception

Change-Id: I99e44fb87d06d5b2001eee892cb25dc973e554f5
Signed-off-by: Andrew Geissler <openbmcbump-github@yahoo.com>