phosphor-pid-control: srcrev bump f7575a7001..e7507a8b55
Patrick Williams (1):
      exception: switch to public sdbus exception

Paul Fertser (1):
      configure.md: add stepwise documentation

Change-Id: I48bd89f91cc2fd88d14e9d1ccb40aceadc12fc5f
Signed-off-by: Andrew Geissler <openbmcbump-github@yahoo.com>