meta-nuvoton: trusted-firmware-a: fix the version at v2.9.0
Currently, openbmc upstream already update tfa to version v2.10.0
For compatibling with latest openbmc, we need to fix the version at v2.9.0. Otherwise, we will meet this kind of build error from upstream.

ERROR: No recipes in default available for:
openbmc/meta-nuvoton/dynamic-layers/arm-layer/recipes-bsp/
trusted-firmware-a/trusted-firmware-a_2.9.%.bbappend

Signed-off-by: Tim Lee <timlee660101@gmail.com>
Change-Id: If652ee5478cc9c42e833dd4d2a203d7d5ebddca1