sdbusplus: srcrev bump 4e82142cb3..456eac0124
Manojkiran Eda (1):
      Remove setup.cfg file from the repository

Oliver Brewka (2):
      utility: Fix type deduction for std::index_sequence
      utility: Add missing include

Patrick Williams (3):
      sdbus++: add interface serialization
      sdbus++: interface: add interface_type name to properties_t
      exception: add event extensions

Change-Id: Ia90d624c230aad42ff0a12f4e857433fed1c74ca
Signed-off-by: Andrew Geissler <openbmcbump-github@yahoo.com>