phosphor-logging: srcrev bump 36a3469323..b2e541ee25
Patrick Williams (2):
      exception: define get_errno for example types
      exception: switch to public sdbus exception

Sumit Kumar (1):
      PEL: Update bmc & platform dump status in SRC section

Vijay Lobo (1):
      PEL.Entry update hidden property setting

Change-Id: Ic9405903c5fcd294317b8c6bc81d1a075c872731
Signed-off-by: Andrew Geissler <openbmcbump-github@yahoo.com>