Fix the CFLAG_append entry in .bb files
Error: configure: error: C compiler cannot create executables

Note: The previous setting was not appending to the CFLAGS
entry. Thus causing compile errors. After testing various
ways to append to the CFLAGS, we chose this approach as
it is most intuitive.

Change-Id: Id81af5666b173aca35eb28f541a8325db1d438fd
Signed-off-by: Saqib Khan <khansa@us.ibm.com>