openpower-occ-control: srcrev bump a26f152793..25613624ce
Patrick Williams (2):
      dos2unix conversion
      exception: switch to public sdbus exception

Change-Id: I8ab78ffe63667b73c2dfb5159173e1fb1f7b1c84
Signed-off-by: Andrew Geissler <openbmcbump-github@yahoo.com>