meta-phosphor: mctp: Add mctp-demux.socket
Resolves the following build error:

ERROR: mctp-1.0+git999-r1 do_package: QA Issue: mctp: Files/directories were installed but not shipped in any package:
  /lib/systemd/system/mctp-demux.socket

Fixes: a27a2f267548 ("libmctp: srcrev bump 507ba00dad..d4103f8f55")
Signed-off-by: George Liu <liuxiwei@inspur.com>
Change-Id: Ib302725bc54c312fc78caf00fa0fa5a2559668c5