meta-ibm: remove ibmtpm2tss
This package does not currently support openssl v3:

| TpmToOsslMath.h:79:5: error: #error Untested OpenSSL version
|    79 | #   error Untested OpenSSL version
|       |     ^~~~~

For now, remove this package so we can make forward progress with
openssl v3 in openbmc.

The following issue appears to be tracking support:
https://sourceforge.net/p/ibmswtpm2/tickets/18/

Signed-off-by: Andrew Geissler <geissonator@yahoo.com>
Change-Id: I2249c323b8219525dcef856d8ceab63de417e299