openpower-debug-collector: srcrev bump a1ea5e5f18..9b6f8474a4
Patrick Williams (1):
      exception: switch to public sdbus exception

Change-Id: I65e07d8dfb54ccc5d6f028683f61ebd4b92b1122
Signed-off-by: Andrew Geissler <openbmcbump-github@yahoo.com>