slpd-lite: srcrev bump ef078cd0d5..43dc41fbcd
Patrick Williams (10):
      bootstrap: fix shellcheck warnings
      prettier: reformat markdown
      clang-format: update with latest
      configure: make SERVICE_DIR static
      OWNERS: switch 'matches' to 'matchers'
      MAINTAINERS: remove file
      error: fix handling of error codes
      main: fix 'unused-parameter' warnings
      slp_parser: fix missing-field-initializers warnings
      build: add meson support

Change-Id: I33abfcdeb7e6d0f21554fd33744daf8b1edbeb20
Signed-off-by: Andrew Geissler <openbmcbump-github@yahoo.com>